### ISSUE TITLE
Build of 0.4.0 failed to publish to maven central

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/jzarr#11]
* [x] blosc results differ (see below)
* [x] why did only the maven build fail??

https://github.com/zarr-developers/jzarr/actions/runs/5335179085/jobs/9668035098#step:5:1412

```
Warning:  Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.011 s - in com.bc.zarr.BloscCompressorTest
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    ZarrArrayTest_saveMultithreading.parallelWriting_toTheSameChunk_withCompression_blosc:101->multithreaded_write_read_roundtrip:154 
Expected: is <0>
     but: was <19>
Error:    ZarrArrayTest_saveMultithreading.parallelWriting_toTheSameChunk_withCompression_blosc_With_ZipStore:83->multithreaded_write_read_roundtrip:154 
Expected: is <0>
     but: was <19>
[INFO] 
Error:  Tests run: 156, Failures: 2, Errors: 0, Skipped: 1
```

cc: @melissalinkert @pedson @MSankeys963

**Comment by melissalinkert** [comment]
https://github.com/zarr-developers/jzarr/blob/main/.github/workflows/deploy.yml doesn't install `libblosc`, but https://github.com/zarr-developers/jzarr/blob/main/.github/workflows/build.yml does. If I read correctly, 0.4.0 is the first release to include https://github.com/zarr-developers/jzarr/pull/2, which fixed how tests were detected.

**Comment by joshmoore** [comment]
Well, that explains the second point. Thanks, @melissalinkert. Okie. I'll get a 0.4.1 ready and 0.4.0 will have to just be out in the aether.

(and/or I delete the tag :wink:)

**Comment by joshmoore** [comment]
Ok. I've deleted the 0.4.0 tag and release. Closing this and we can move forward with #12 when ready.
