### ISSUE TITLE
Unexpected keyword argument 'numThreads' when reading Java Zarr with Python

### ISSUE THREAD

**Issue by ZigzagAwaka** [zarr-developers/jzarr#14]
Hi,

When creating Blosc compressor with
```
Compressor compressor = CompressorFactory.create("blosc", "cname", "zstd", "clevel", 9, "blocksize", 0, "shuffle", 1);
```
A new optional parameter for Blosc "nthreads" is added into the .zarray metadata file as
```
"numThreads" : 1
```
And this is what I got when reading this Zarr with the Python API
```
  File "numcodecs\blosc.pyx", line 548, in numcodecs.blosc.Blosc.__init__
TypeError: __init__() got an unexpected keyword argument 'numThreads'
```
<p>

Since 'numThreads' is in metadata files it's not possible anymore to read the resulting Zarr using Python
It's technically a Python error, but since JZarr data has to be compatible with the Python API I think it's more of a Java issue (or did I just do something wrong ?)

**Comment by joshmoore** [comment]
Thanks for the issue, @ZigzagAwaka. #15 should solve this issue once released. (If it doesn't, please let us know)
